//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string OriginalFileName { get; set; }
        public string QrCodeFileName { get; set; }
        public Nullable<int> Size { get; set; }
        public string RequestIp { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> NumberOfViews { get; set; }
    }
}
